configfile: "config.yaml"

samples = config["samples"]

rule all:
    input:
        expand("output/images/network/{sample}_spras.png", sample=samples),
        expand("output/images/network/{sample}_panther.png", sample=samples),
        expand("output/stats/edges/{sample}_stats.txt", sample=samples),
        expand("output/stats/score/{sample}.txt", sample=samples),
        expand("output/images/auc/{sample}_roc.png", sample=samples),
        expand("output/images/auc/{sample}_pr.png", sample=samples),

rule pathway_image:
    input:
        spras=lambda wildcards: f"networks/{wildcards.sample}/spras.txt",
        panther=lambda wildcards: f"networks/{wildcards.sample}/panther.txt"
    output:
        spras_image="output/images/network/{sample}_spras.png",
        panther_image="output/images/network/{sample}_panther.png"
    script:
        "scripts/generate_network.py"

rule pathway_stats:
    input:
        spras=lambda wildcards: f"networks/{wildcards.sample}/spras.txt",
        panther=lambda wildcards: f"networks/{wildcards.sample}/panther.txt"
    output:
        stats="output/stats/edges/{sample}_stats.txt"
    script:
        "scripts/generate_stats.py"

rule generate_scores:
    input:
        spras=lambda wildcards: f"networks/{wildcards.sample}/spras.txt",
        panther=lambda wildcards: f"networks/{wildcards.sample}/panther.txt"
    output:
        score="output/stats/score/{sample}.txt",
    script:
        "scripts/generate_scores_file.py"

rule generate_auc_image:
    input:
        score=lambda wildcards: f"output/stats/score/{wildcards.sample}.txt",
    output:
        roc="output/images/auc/{sample}_roc.png",
        pr="output/images/auc/{sample}_pr.png",
    script:
        "scripts/generate_auc.py"