# The length of the hash used to identify a parameter combination
hash_length: 7

# If true, use Singularity instead of Docker
# Singularity support is only available on Unix
singularity: false

algorithms:
  - name: pathlinker
    params:
      include: false
      run1:
        k:
          - 10
          - 20
  - name: omicsintegrator1
    params:
      include: true
      run1:
        b:
          - 2
          - 4
          - 7
          - 10
        d:
          - 10
        g:
          - 1e-3
        r:
          - 0.01
        w:
          - 0.1
          - 1
        mu:
          - 0.01
          - 0.1
        dummy_mode: ["terminal"]
  - name: omicsintegrator2
    params:
      include: true
      run1:
        b:
          - 4
        g:
          - 0
      run2:
        b:
          - 2
        g:
          - 3
  - name: meo
    params:
      include: false
      run1:
        local_search:
          - "Yes"
        max_path_length:
          - 3
        rand_restarts:
          - 10
  - name: domino
    params:
      include: false
      run1:
        slice_threshold:
          - 0.3
        module_threshold:
          - 0.05
datasets:
  - data_dir: input
    edge_files:
      - phosphosite-irefindex13.0-uniprot.txt
    label: cellline
    node_files:
      - cellline_fadu_nodes.txt
    other_files: []
reconstruction_settings:
  locations:
    reconstruction_dir: output/cellline_fadu
  run: true
analysis:
  graphspace:
    include: false
  cytoscape:
    include: true
  summary:
    include: true
  ml:
    include: false
  evaluation:
    include: false
