[type.txt]
# Ignore data files
extend-glob = ["*.jsonc", "*.json"]
check-file = false

[files]
extend-exclude = [
    # PANTHER SPRAS formatting contains an intentional typo
    "datasets/synthetic_data/scripts/panther_spras_formatting.py",
    # Bad variable names in this file that may be removed later
    "datasets/diseases/viz/viz.ipynb"
]
