"""
This Snakefile is not meant to be ran - rather, it is meant to be imported by
other Snakefiles. This can't be a Python script since it uses rule generation in
`produce_fetch_rules`.
"""

from cache import FetchConfig, link, stringify_config
from cache.directory import CacheItem # for exposing to Snakefiles that import this Snakefile.
from cache.util import uncompress
import urllib.parse
from typing import Union
from pathlib import Path

def produce_fetch_rules(input_dict: dict[str, Union[FetchConfig, list[str]]]):
    """
    Produces fetch rules based on a dictionary mapping
    output files to their directory.py-based directive.
    """
    # Map inputs to be wrapped with FetchConfig if tuple[str, ...] or CacheItem
    input_dict = {k: FetchConfig(v) if isinstance(v, tuple) or isinstance(v, CacheItem) else v for k, v in input_dict.items()}

    directives = list(input_dict.values())
    assert len(directives) == len(set(directives)), "Directives aren't unique!"

    for output_file, config in input_dict.items():
        # Since placeholders are evaluated when the job is actually ran,
        # we pass data using params and output.
        rule:
            name:
                f"fetch_{stringify_config(config.directive)}_to_{urllib.parse.quote_plus(output_file)}"
            output: file=output_file
            params:
                config=config
            run:
                Path(output.file).parent.mkdir(exist_ok=True)
                link(Path(output.file), params.config)
