# Global workflow control

hash_length: 7
container_framework: docker
unpack_singularity: false

container_registry:
   base_url: docker.io
   owner: reedcompbio

algorithms:
      - name: "omicsintegrator1"
        params:
              include: true
              run1:
                  b: [2]
                  w: [.5]
                  d: [10]
                  mu: [2]

datasets:
    -
      label: hiv060
      node_files: ["modified_prize_060.txt"]
      # DataLoader.py can currently only load a single edge file, which is the primary network
      edge_files: ["phosphosite-irefindex13.0-uniprot.txt"]
      # Placeholder
      other_files: []
      # Relative path from the spras directory
      data_dir: "hiv-benchmarking/hiv_processed_data"
    - 
      label: hiv05
      node_files: ["modified_prize_05.txt"]
      edge_files: ["phosphosite-irefindex13.0-uniprot.txt"]
      other_files: []
      data_dir: "hiv-benchmarking/hiv_processed_data"
    -
      label: yeast
      node_files: ["prizes1_dummies.txt"]
      # DataLoader.py can currently only load a single edge file, which is the primary network
      edge_files: ["network1.txt"]
      # Placeholder
      other_files: []
      # Relative path from the spras directory
      data_dir: "yeast-osmotic-stress/processed"

# If we want to reconstruct then we should set run to true.
# TODO: if include is true above but run is false here, algs are not run.
# is this the behavior we want?
reconstruction_settings:

        #set where everything is saved
        locations:

              #place the save path here
              # TODO move to global
              reconstruction_dir: "output"

        run: true

analysis:
  summary:
    include: false
  graphspace:
    include: false
  cytoscape:
    include: false
  ml:
    include: false
  evaluation:
    include: false
