name: Test SPRAS

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  pre-commit:
    name: Run pre-commit checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Run pre-commit checks
        uses: pre-commit/action@v3.0.0
  queue:
    name: Add commit to queue
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Deactivate GitHub authentication
        # https://stackoverflow.com/a/69979203/7589775
        run: git config --unset-all http.https://github.com/.extraheader
      - name: Specify github-actions email
        run: git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - name: Specify github-actions username
        run: git config --global user.name "github-actions"
      - name: Use QUEUE_TOKEN
        # https://stackoverflow.com/a/75684635/7589775
        run: /usr/bin/git config --global --add url."https://${{ secrets.QUEUE_TOKEN }}:x-oauth-basic@github".insteadOf https://github
      - name: Run queue appender
        run: python3 queue/amend.py
  checks:
    name: Run workflow
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install uv for scripting
        uses: astral-sh/setup-uv@v6.1.0
        with:
          version: "0.7.13"
      - name: Setup conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: spras
          environment-file: spras/environment.yml
          auto-activate-base: false
          miniconda-version: 'latest'
      # Install spras in the environment using pip
      - name: Install spras in conda env
        shell: bash --login {0}
        run: pip install ./spras
      # Log conda environment contents
      - name: Log conda environment
        shell: bash --login {0}
        run: conda list
      - name: Process raw data through Snakemake
        run: sh run_snakemake.sh
      - name: Run Snakemake workflow for DMMMs
        shell: bash --login {0}
        run: snakemake --cores 1 --configfile configs/dmmm.yaml --show-failed-logs -s spras/Snakefile
      # TODO: re-enable PRAs once RN/synthetic data PRs are merged.
      # - name: Run Snakemake workflow for PRAs
      #   shell: bash --login {0}
      #   run: snakemake --cores 1 --configfile configs/pra.yaml --show-failed-logs -s spras/Snakefile
      - name: Setup PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 10
      - name: Install web dependencies
        working-directory: ./web
        run: pnpm install
      - name: Run web builder
        working-directory: ./web
        run: pnpm build
      - name: Upload built website distribution folder
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: web/dist
  pages:
    needs: checks
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    concurrency:
      group: 'pages'
      cancel-in-progress: true
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: build
          path: dist
      - name: Setup Pages
        uses: actions/configure-pages@v2
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
