name: Test SPRAS

on: [push]

jobs:
  # Runs the Snakemake workflow in the conda environment
  test:
    name: Run workflow
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install conda environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: spras
          environment-file: spras/environment.yml
          auto-activate-base: false
          miniconda-version: 'latest'
      # Install spras in the environment using pip
      - name: Install spras in conda env
        shell: bash --login {0}
        run: pip install ./spras
      # Log conda environment contents
      - name: Log conda environment
        shell: bash --login {0}
        run: conda list
      - name: Run Snakemake workflow
        shell: bash --login {0}
        run: snakemake --cores 1 --configfile configs/config.yaml --show-failed-logs -s spras/Snakefile
      - name: Checkout /output
        run: ls /output
