name: Test SPRAS

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  checks:
    name: Run workflow
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install conda environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: spras
          environment-file: spras/environment.yml
          auto-activate-base: false
          miniconda-version: 'latest'
      # Install spras in the environment using pip
      - name: Install spras in conda env
        shell: bash --login {0}
        run: pip install ./spras
      # Log conda environment contents
      - name: Log conda environment
        shell: bash --login {0}
        run: conda list
      - name: Run Snakemake workflow for DMMMs
        shell: bash --login {0}
        run: snakemake --cores 1 --configfile configs/base.yaml --configfile configs/dmmm.yaml --show-failed-logs -s spras/Snakefile
      - name: Run output viewer
        run: python3 web/generate.py
      - name: Upload built project output
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: web/output
  pages:
    needs: checks
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          download-path: output
      - name: Setup Pages
        uses: actions/configure-pages@v2
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: output
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
